
module.exports.routes = {

  'PUT /v1/users' : 'UserController.singin',
  'POST /v1/users' : 'UserController.login',
  'GET /v1/pairing' : 'PairingController.pairing',
  'PUT /v1/preferences' : 'PreferencesController.update',
  'GET /v1/preferences' : 'PreferencesController.select',
  'PUT /v1/settings' : 'SettingsController.update',
  'GET /v1/settings' : 'SettingsController.select',
  'PUT /v1/location' : 'LocationController.update',
  'GET /v1/location' : 'LocationController.select',
  'PUT /v1/like' : 'LikeController.like',
  'GET /v1/like' : 'LikeController.select',
  'PUT /v1/deslike' : 'DeslikeController.deslike',
  'GET /v1/deslike' : 'DeslikeController.select',
  "GET /v1/health" : "HealthController.health",
  "PUT /v1/superLike" : "SuperLikesController.superLike",
  "GET /v1/superLike" : "SuperLikesController.select",
  "GET /v1/match" : "MatchController.select",
  "DELETE /v1/match" : "MatchController.delete",
  "POST /v1/chat" : "ChatController.accessRequest",
  "PUT /v1/chat" : "ChatController.addMsg",
  "GET /v1/chat" : "ChatController.getMsgs",
  // "POST /v1/uploadFile" : "FilesController.upload",
  // "POST /v1/downloadFile" : "FilesController.download",
  // "GET /v1/getFiles" : "FilesController.getFiles",
};
